cameras:
  cam_1:
    enabled: true
    detect:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://root:root@111.70.33.189:554/axis-media/media.amp
          roles:
            - record
    record:
      enabled: true
    motion:
      enabled: false
  cam_2:
    enabled: true
    detect:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_CAM2_PASSWORD}@111.70.34.183:6554/profile2/media.smp
          roles:
            - record
    record:
      enabled: true
    motion:
      enabled: true
      threshold: 25
      contour_area: 20
detect:
  enabled: false
detectors:
  cpu1:
    type: cpu
ffmpeg:
  hwaccel_args: []
  output_args:
    record: preset-record-generic-audio-copy
mqtt:
  enabled: false
record:
  enabled: true
  continuous:
    days: 3
  motion:
    days: 7
snapshots:
  enabled: false
version: 0.17-0
